### ISSUE TITLE
AddressProvider-ng

### ISSUE THREAD

**Issue by bout3fiddy** [curvefi/metaregistry#19]
# Background

Currently Curve has an Address Provider contract on most chains (not all), deployed deterministically at: [0x0000000022d53366457f9d5e68ec105046fc4383](https://etherscan.io/address/0x0000000022d53366457f9d5e68ec105046fc4383#code). This contract is a simply 'entrypoint' contract that guides integrators to other assets belonging to curve, such that they could use it as an on-chain API of on-chain APIs.

New AddressProvider entries are added via [`add_new_id`](https://etherscan.io/address/0x0000000022d53366457f9d5e68ec105046fc4383#writeContract#F1), callable only by the admin, which is currently a thin proxy contract deployed at [0xEdf2C58E16Cc606Da1977e79E1e69e79C54fe242](https://etherscan.io/address/0xEdf2C58E16Cc606Da1977e79E1e69e79C54fe242#readContract), owned by Curve Core Devs.

Each new ID added to the AddressProvider cannot be unset.

# Challenges

1. The current deployer used to deploy the AddressProvider is unavailable. This means AddressProvider contracts cannot be deterministically deployed to new chains.
2. The AddressProvider contract does have a method to unset an address set at a particular ID but not change its description. This means that ID (s) cannot be repurposed.

# Proposed Solution

1. We re-do the AddressProvider with create2 deployer. Optionally, we can mine salts for vanity addresses using [CreateXCrunch](https://github.com/HrikB/createXcrunch).
2. New IDs in the improved AddressProvider contract can be re-purposed entirely such that the description of an existing ID can be changed as well.
3. The newly deployed AddressProvider IDs shall have the same ID designation across all chains. This could perhaps be achieved by changing the index of the ID hashmap from uint256 to bytes32, where the generated bytes32 is a keccak hash of the name of the contract.

# Task List

- [ ] Add a new method to AddressProvider to change the description of an ID
- [ ] (optional) mine salts for create2 deployment
- [ ] deploy across _all_ networks Curve has presence
- [ ] set AddressProvider IDs to be the same across all chains.
